repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts:
          - "validate"
          - "build"
      enforce_admins: false
      restrictions: null
      required_linear_history: true
      required_conversation_resolution: true

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "validate"
          - "build"
      enforce_admins: false
      restrictions: null
