// Mock data for featured venues following the project's DTO pattern
import type { FeaturedListingDTO } from '@/types/dto';

export const mockFeaturedVenues: FeaturedListingDTO[] = [
  {
    id: 'banyan-tree-phuket',
    name: 'Banyan Tree Phuket',
    slug: 'banyan-tree-phuket',
    imageUrl: '/placeholder_image.png',
    city: 'Phuket',
    amenityNames: [
      'Solar Powered',
      'Zero Waste',
      'Local Sourcing',
      'High-Speed WiFi',
      'Coworking Space',
      'Meeting Rooms',
    ],
  },
  {
    id: 'katathani-phuket-beach-resort',
    name: 'Katathani Phuket Beach Resort',
    slug: 'katathani-phuket-beach-resort',
    imageUrl: '/placeholder_image.png',
    city: 'Phuket',
    amenityNames: [
      'Ocean Conservation',
      'Renewable Energy',
      'Sustainable Tourism',
      'Business Center',
      'WiFi Throughout',
      'Quiet Work Areas',
    ],
  },
  {
    id: 'alt-chiangmai-coworking',
    name: 'Alt_ChiangMai Coworking & Coliving / Alt_PingRiver',
    slug: 'alt-chiangmai-coworking',
    imageUrl: '/placeholder_image.png',
    city: 'Chiang Mai',
    amenityNames: [
      'Green Building',
      'Community Garden',
      'Bike Friendly',
      '24/7 Access',
      'High-Speed Internet',
      'Community Events',
    ],
  },
  {
    id: 'the-yard-hostel',
    name: 'The Yard Hostel',
    slug: 'the-yard-hostel',
    imageUrl: '/placeholder_image.png',
    city: 'Bangkok',
    amenityNames: [
      'Recycled Materials',
      'Urban Garden',
      'Composting',
      'Community Kitchen',
      'Free Bicycles',
      'High-Speed WiFi',
    ],
  },
  {
    id: 'd-well-hostel',
    name: 'D-Well Hostel',
    slug: 'd-well-hostel',
    imageUrl: '/placeholder_image.png',
    city: 'Chiang Mai',
    amenityNames: [
      'Energy-Efficient',
      'Water Conservation',
      'Rooftop Terrace',
      'Coworking Area',
      'High-Speed WiFi',
      'Secure Lockers',
    ],
  },
  {
    id: 'green-tiger-house',
    name: 'Green Tiger House',
    slug: 'green-tiger-house',
    imageUrl: '/placeholder_image.png',
    city: 'Chiang Mai',
    amenityNames: [
      'Vegetarian Restaurant',
      'Solar Hot Water',
      'No Single-Use Plastic',
      'Yoga Classes',
      'Free WiFi',
      'Tour Desk',
    ],
  },
  {
    id: 'hub53',
    name: 'Hub53 Coworking and Coliving Space',
    slug: 'hub53',
    imageUrl: '/placeholder_image.png',
    city: 'Chiang Mai',
    amenityNames: [
      '24/7 Access',
      'Ergonomic Chairs',
      'Meeting Rooms',
      'Call Rooms',
      'High-Speed WiFi',
      'Community Events',
    ],
  },
  {
    id: 'ko-hub',
    name: 'KohHub',
    slug: 'koh-hub',
    imageUrl: '/placeholder_image.png',
    city: 'Koh Lanta',
    amenityNames: [
      'Beachfront',
      'Coworking Space',
      'Coliving',
      'Restaurant',
      'High-Speed WiFi',
      'Weekly Talks',
    ],
  },
];
