// Generated by Copilot

const CategoriesPage = () => {
  return (
    <div>
      <h1>Categories</h1>
      <p>This is the placeholder page for categories.</p>
    </div>
  );
};

export default CategoriesPage;
