/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: schema.json
export type UserPreference = {
  _id: string
  _type: 'userPreference'
  _createdAt: string
  _updatedAt: string
  _rev: string
  user?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  preferredCategories?: Array<string>
  preferredCities?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'city'
  }>
  preferredEcoTags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'ecoTag'
  }>
  priceRangePreference?: 'budget' | 'midRange' | 'premium'
  notificationPreferences?: {
    email?: boolean
    push?: boolean
    frequency?: 'daily' | 'weekly' | 'monthly'
  }
  lastUpdated?: string
}

export type SearchConfig = {
  _id: string
  _type: 'searchConfig'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fieldBoosts?: {
    name?: number
    description?: number
    ecoTags?: number
    city?: number
  }
  geoSearchSettings?: {
    defaultRadius?: number
    maxRadius?: number
  }
  facetedSearchConfig?: Array<{
    fieldName?: string
    displayName?: string
    type?: 'categorical' | 'range' | 'boolean' | 'date'
    rangeConfig?: {
      min?: number
      max?: number
      step?: number
    }
    categoryConfig?: {
      multiSelect?: boolean
      showCount?: boolean
    }
    _key: string
  }>
  sortOptions?: Array<{
    field?: string
    displayName?: string
    direction?: 'asc' | 'desc'
    _key: string
  }>
  performanceSettings?: {
    cacheDuration?: number
    maxResults?: number
    paginationSize?: number
  }
}

export type SearchBoost = {
  _id: string
  _type: 'searchBoost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  boost?: number
  description?: string
}

export type RichText = {
  _type: 'richText'
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              href?: string
              blank?: boolean
              _type: 'link'
              _key: string
            }
          | {
              reference?:
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'listing'
                  }
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'blogPost'
                  }
              _type: 'internalReference'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  excerpt?: string
  metadata?: {
    keywords?: Array<string>
    readTime?: number
  }
}

export type RestaurantDetails = {
  _type: 'restaurantDetails'
  cuisineType?: Array<string>
  priceRange?: 'budget' | 'moderate' | 'expensive' | 'luxury'
  operatingHours?: string
  sustainabilityInitiatives?: Array<string>
  dietaryOptions?: Array<string>
  seating?: Array<string>
  workFriendly?: Array<string>
  averageMealPriceThb?: {
    min?: number
    max?: number
  }
}

export type NomadFeature = {
  _id: string
  _type: 'nomadFeature'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  icon?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
}

export type ModerationStatus = {
  _id: string
  _type: 'moderationStatus'
  _createdAt: string
  _updatedAt: string
  _rev: string
  item?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'listing'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'review'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'comment'
      }
  status?: 'pending' | 'approved' | 'rejected' | 'changes_needed' | 'flagged'
  moderatorNotes?: string
  moderatedBy?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  moderatedAt?: string
  userReports?: Array<{
    reportedBy?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'user'
    }
    reason?: string
    details?: string
    reportedAt?: string
    _key: string
  }>
}

export type ListingAnalytics = {
  _id: string
  _type: 'listingAnalytics'
  _createdAt: string
  _updatedAt: string
  _rev: string
  listing?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'listing'
  }
  viewCount?: number
  bookmarkCount?: number
  clickThroughRate?: number
  lastUpdated?: string
  timeOnPage?: number
}

export type EventRegistration = {
  _id: string
  _type: 'eventRegistration'
  _createdAt: string
  _updatedAt: string
  _rev: string
  event?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'event'
  }
  user?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  registrationDate?: string
  status?: 'pending' | 'confirmed' | 'cancelled' | 'attended'
  notes?: string
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  venue?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'listing'
  }
  startDate?: string
  endDate?: string
  city?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'city'
  }
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  link?: string
}

export type EcoInitiatives = {
  _type: 'ecoInitiatives'
  sustainableEnergy?: 'fully_renewable' | 'partially_renewable' | 'energy_efficient' | 'standard'
  wasteManagement?: boolean
  waterConservation?: boolean
  localSourcing?: boolean
  plasticFree?: boolean
  veganOptions?: boolean
  certifications?: Array<string>
  additionalInitiatives?: Array<string>
}

export type CoworkingDetails = {
  _type: 'coworkingDetails'
  operatingHours?: string
  pricingPlans?: Array<{
    type?: 'daily' | 'weekly' | 'monthly' | 'hot-desk' | 'dedicated-desk' | 'private-office'
    price?: number
    currency?: string
    _key: string
  }>
  internetSpeed?: {
    download?: number
    upload?: number
    lastTested?: string
  }
}

export type Comment = {
  _id: string
  _type: 'comment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'blogPost'
  }
  user?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  content?: string
  createdAt?: string
  approved?: boolean
  parent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'comment'
  }
}

export type CafeDetails = {
  _type: 'cafeDetails'
  operatingHours?: Array<{
    day?: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'
    openTime?:
      | '00:00'
      | '01:00'
      | '02:00'
      | '03:00'
      | '04:00'
      | '05:00'
      | '06:00'
      | '07:00'
      | '08:00'
      | '09:00'
      | '10:00'
      | '11:00'
      | '12:00'
      | '13:00'
      | '14:00'
      | '15:00'
      | '16:00'
      | '17:00'
      | '18:00'
      | '19:00'
      | '20:00'
      | '21:00'
      | '22:00'
      | '23:00'
    closeTime?:
      | '00:00'
      | '01:00'
      | '02:00'
      | '03:00'
      | '04:00'
      | '05:00'
      | '06:00'
      | '07:00'
      | '08:00'
      | '09:00'
      | '10:00'
      | '11:00'
      | '12:00'
      | '13:00'
      | '14:00'
      | '15:00'
      | '16:00'
      | '17:00'
      | '18:00'
      | '19:00'
      | '20:00'
      | '21:00'
      | '22:00'
      | '23:00'
    closed?: boolean
    _key: string
  }>
  priceIndication?: '$' | '$$' | '$$$' | '$$$$'
  menuHighlights?: Array<
    | 'specialty_coffee_beans'
    | 'sourdough_bread_pastries'
    | 'extensive_vegan_options'
    | 'fresh_pressed_juices_smoothies'
    | 'brunch_menu'
    | 'local_thai_dishes'
    | 'craft_beer_wine'
    | 'organic_ingredients'
    | 'gluten_free_options'
    | 'plant_based_menu'
  >
  workspaceAmenities?: Array<string>
  maxRecommendedStay?: number
  noiseLevel?: 'very_quiet' | 'low' | 'moderate' | 'high' | 'very_loud'
  powerOutlets?: {
    availability?: 'abundant' | 'good' | 'limited' | 'very_limited' | 'none'
    notes?: string
  }
  workPolicy?: {
    laptopsAllowed?: boolean
    timeLimit?: number
    peakHoursPolicy?: 'always' | 'limited_peak' | 'no_peak'
    peakHours?: string
  }
  veganFriendly?: {
    isVeganFriendly?: boolean
    veganOptions?: number
  }
}

export type Amenities = {
  _type: 'amenities'
  wifiQuality?: 'high_speed' | 'good' | 'basic' | 'limited' | 'none'
  wifiSpeed?: number
  powerOutlets?: 'abundant' | 'limited' | 'none'
  seating?: 'comfortable' | 'standard' | 'limited'
  airConditioning?: boolean
  quietSpace?: boolean
  meetingRooms?: boolean
  phoneBooths?: boolean
  printers?: boolean
  parking?: boolean
  bikeParking?: boolean
  showers?: boolean
  lockers?: boolean
  kitchen?: boolean
  additionalAmenities?: Array<string>
}

export type Address = {
  _type: 'address'
  streetAddress?: string
  city?: string
  province?: string
  postalCode?: string
}

export type ActivitiesDetails = {
  _type: 'activitiesDetails'
  activityType?:
    | 'yoga_wellness'
    | 'outdoor_adventure'
    | 'cultural_experience'
    | 'eco_tour'
    | 'cooking_class'
    | 'meditation_mindfulness'
    | 'community_service'
    | 'sustainable_workshop'
  pricePerPerson?: {
    min?: number
    max?: number
  }
  duration?: {
    value?: number
    unit?: 'hours' | 'days'
  }
  groupSize?: {
    min?: number
    max?: number
  }
  sustainabilityPractices?: Array<string>
  skillLevel?: 'beginner' | 'intermediate' | 'advanced' | 'all_levels'
  ecoScore?: {
    score?: number
    certifications?: Array<string>
    justification?: string
  }
  languages?: Array<string>
  accessibility?: {
    wheelchairAccessible?: boolean
    mobilityLevel?: 'easy' | 'moderate' | 'challenging' | 'difficult'
    accessibilityNotes?: string
  }
  seasonality?: {
    bestMonths?: Array<string>
    weatherDependent?: boolean
  }
}

export type AccommodationDetails = {
  _type: 'accommodationDetails'
  accommodationType?:
    | 'hotel'
    | 'guesthouse'
    | 'bungalow'
    | 'resort'
    | 'hostel'
    | 'apartment_condo'
    | 'villa'
    | 'eco_lodge'
  priceRangeThb?: {
    min?: number
    max?: number
  }
  roomTypesAvailable?: Array<{
    type?:
      | 'single'
      | 'double'
      | 'twin'
      | 'studio'
      | 'one_bedroom'
      | 'two_bedroom'
      | 'dormitory'
      | 'suite'
    pricePerNight?: number
    features?: Array<string>
    _key: string
  }>
  minimumStay?: number
  coworkingPartnership?: {
    hasPartnership?: boolean
    partner?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'listing'
    }
    discountDetails?: string
  }
  workspaceQuality?: {
    hasWorkspace?: boolean
    workspaceType?: 'proper_desk' | 'ergonomic' | 'basic' | 'shared'
    workspaceFeatures?: Array<string>
  }
  stayDuration?: {
    minimumNights?: number
    maximumNights?: number
    longTermAvailable?: boolean
    longTermDiscount?: string
  }
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  publishedAt?: string
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  excerpt?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  tags?: Array<string>
}

export type User = {
  _id: string
  _type: 'user'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  avatar?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: string
  role?: 'user' | 'editor' | 'venueOwner' | 'admin'
  ownedListings?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'listing'
  }>
  reviews?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'review'
  }>
  lastActive?: string
  createdAt?: string
}

export type Review = {
  _id: string
  _type: 'review'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author?: string
  rating?: number
  comment?: string
  date?: string
}

export type EcoTag = {
  _id: string
  _type: 'ecoTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
}

export type Listing = {
  _id: string
  _type: 'listing'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  city?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'city'
  }
  type?: 'coworking' | 'cafe' | 'accommodation' | 'restaurant' | 'activities'
  address?: string
  location?: Geopoint
  shortDescription?: string
  longDescription?: string
  ecoTags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'ecoTag'
  }>
  ecoNotesDetailed?: string
  sourceUrls?: Array<string>
  primaryImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  galleryImages?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  digitalNomadFeatures?: Array<string>
  lastVerifiedDate?: string
  coworkingDetails?: {
    operatingHours?: string
    pricingPlans?: Array<string>
    specificAmenitiesCoworking?: Array<string>
  }
  cafeDetails?: {
    operatingHours?: string
    priceIndication?: string
    menuHighlightsCafe?: Array<string>
    wifiReliabilityNotes?: string
  }
  accommodationDetails?: {
    accommodationType?: string
    pricePerNightThbRange?: string
    roomTypesAvailable?: Array<string>
    specificAmenitiesAccommodation?: Array<string>
  }
  reviews?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'review'
  }>
  moderation?: {
    status?: 'draft' | 'pending' | 'published' | 'archived' | 'flagged'
    featured?: boolean
    verificationStatus?: 'unverified' | 'verified' | 'needs_verification'
    moderatorNotes?: string
  }
  searchMetadata?: {
    keywords?: Array<string>
    boost?: number
    searchExcerpt?: string
    similarListings?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'listing'
    }>
  }
  ecoDetails?: {
    description?: string
    ecoTags?: Array<string>
    certifications?: Array<string>
  }
  moderationStatus?: 'pending' | 'approved' | 'rejected'
  verificationStatus?: 'unverified' | 'verified'
}
export type City = {
  _id: string
  _type: 'city'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  country?: string
  description?: string
  sustainabilityScore?: number
  highlights?: Array<string>
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | UserPreference
  | SearchConfig
  | SearchBoost
  | RichText
  | RestaurantDetails
  | NomadFeature
  | ModerationStatus
  | ListingAnalytics
  | EventRegistration
  | Event
  | EcoInitiatives
  | CoworkingDetails
  | Comment
  | CafeDetails
  | Amenities
  | Address
  | ActivitiesDetails
  | AccommodationDetails
  | BlogPost
  | User
  | Review
  | EcoTag
  | Listing
  | City
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
// Source: ../app-next-directory/src/lib/sanity/data.ts
// Variable: LISTING_BY_SLUG_QUERY
// Query: *[_type == "listing" && slug.current == $slug][0] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    name,    "slug": slug.current,    shortDescription,    longDescription,    category,    city->{      _id,      title,      "slug": slug.current    },    location { lat, lng },    primaryImage,    ecoTags,    digitalNomadFeatures,    lastVerifiedDate,    reviews[]->,    address,    website,    contactInfo,    openingHours,    shortDescription,    sourceUrls,    rating,    priceRange,    galleryImages[]{      ...,      asset->    }  }
export type LISTING_BY_SLUG_QUERYResult = {
  _id: string
  _type: 'listing'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string | null
  slug: string | null
  shortDescription: string | null
  longDescription: string | null
  category: null
  city: {
    _id: string
    title: null
    slug: string | null
  } | null
  location: {
    lat: number | null
    lng: number | null
  } | null
  primaryImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  } | null
  ecoTags: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'ecoTag'
  }> | null
  digitalNomadFeatures: Array<string> | null
  lastVerifiedDate: string | null
  reviews: Array<{
    _id: string
    _type: 'review'
    _createdAt: string
    _updatedAt: string
    _rev: string
    author?: string
    rating?: number
    comment?: string
    date?: string
  }> | null
  address: string | null
  website: null
  contactInfo: null
  openingHours: null
  sourceUrls: Array<string> | null
  rating: null
  priceRange: null
  galleryImages: Array<{
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }> | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "listing" && slug.current == $slug][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    name,\n    "slug": slug.current,\n    shortDescription,\n    longDescription,\n    category,\n    city->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    location { lat, lng },\n    primaryImage,\n    ecoTags,\n    digitalNomadFeatures,\n    lastVerifiedDate,\n    reviews[]->,\n    address,\n    website,\n    contactInfo,\n    openingHours,\n    shortDescription,\n    sourceUrls,\n    rating,\n    priceRange,\n    galleryImages[]{\n      ...,\n      asset->\n    }\n  }\n': LISTING_BY_SLUG_QUERYResult
    // Duplicate declaration removed to fix TS2717 error
  }
}
