/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/api/blog/[slug]/route.ts
// Variable: postQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id,    title,    slug,    mainImage,    publishedAt,    excerpt,    body,    tags,    "authorName": author->name,    "authorImage": author->image,    "authorBio": author->bio,    "readingTime": round(length(pt::text(body)) / 200),    "relatedPosts": *[_type == "blogPost" && slug.current != $slug && count(tags[@ in ^.tags]) > 0] | order(publishedAt desc) [0...3] {      _id,      title,      slug,      mainImage,      publishedAt,      excerpt,      "authorName": author->name    },    _createdAt,    _updatedAt  }
export type PostQueryResult = null;

// Source: ./app/api/blog/route.ts
// Variable: postsQuery
// Query: *[_type == "blogPost" && defined(slug)] | order(publishedAt desc) [$start...$end] {    _id,    title,    slug,    mainImage,    publishedAt,    excerpt,    tags,    "authorName": author->name,    "authorImage": author->image,    "readingTime": round(length(pt::text(body)) / 200),    _updatedAt  }
export type PostsQueryResult = Array<never>;
// Variable: countQuery
// Query: count(*[_type == "blogPost" && defined(slug)])
export type CountQueryResult = number;

// Source: ./app/api/cities/route.ts
// Variable: CITIES_QUERY
// Query: *[_type == "city"] | order(_createdAt desc)[0...20] {      _id,      title,      "slug": slug.current,      country,      sustainabilityScore,      "mainImage": mainImage {        alt,        "asset": asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      }    }
export type CITIES_QUERYResult = Array<never>;

// Source: ./app/api/featured-listings/route.ts
// Variable: FEATURED_LISTINGS_QUERY
// Query: *[_type == "listing" && moderation.featured == true && moderation.status == "published"] | order(_createdAt desc)[0...10] {      _id,      name,      "slug": slug.current,      "primaryImage": primaryImage{        alt,        "asset": asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      },      "galleryImages": galleryImages[0]{        alt,        "asset": asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      },      "location": city->{        _id,        name,        country      },      price    }
export type FEATURED_LISTINGS_QUERYResult = Array<never>;

// Source: ./src/lib/sanity/data.ts
// Variable: LISTING_BY_SLUG_QUERY
// Query: *[_type == "listing" && slug.current == $slug][0] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    name,    "slug": slug.current,    shortDescription,    longDescription,    category,    city->{      _id,      title,      "slug": slug.current    },    location { lat, lng },    primaryImage,    ecoTags,    digitalNomadFeatures,    lastVerifiedDate,    reviews[]->,    address,    website,    contactInfo,    openingHours,    shortDescription,    sourceUrls,        priceRange,    galleryImages[]{      ...,      asset->    }  }
export type LISTING_BY_SLUG_QUERYResult = null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    excerpt,\n    body,\n    tags,\n    "authorName": author->name,\n    "authorImage": author->image,\n    "authorBio": author->bio,\n    "readingTime": round(length(pt::text(body)) / 200),\n    "relatedPosts": *[_type == "blogPost" && slug.current != $slug && count(tags[@ in ^.tags]) > 0] | order(publishedAt desc) [0...3] {\n      _id,\n      title,\n      slug,\n      mainImage,\n      publishedAt,\n      excerpt,\n      "authorName": author->name\n    },\n    _createdAt,\n    _updatedAt\n  }\n': PostQueryResult;
    '\n  *[_type == "blogPost" && defined(slug)] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    excerpt,\n    tags,\n    "authorName": author->name,\n    "authorImage": author->image,\n    "readingTime": round(length(pt::text(body)) / 200),\n    _updatedAt\n  }\n': PostsQueryResult;
    'count(*[_type == "blogPost" && defined(slug)])': CountQueryResult;
    '*[_type == "city"] | order(_createdAt desc)[0...20] {\n      _id,\n      title,\n      "slug": slug.current,\n      country,\n      sustainabilityScore,\n      "mainImage": mainImage {\n        alt,\n        "asset": asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      }\n    }': CITIES_QUERYResult;
    '*[_type == "listing" && moderation.featured == true && moderation.status == "published"] | order(_createdAt desc)[0...10] {\n      _id,\n      name,\n      "slug": slug.current,\n      "primaryImage": primaryImage{\n        alt,\n        "asset": asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      },\n      "galleryImages": galleryImages[0]{\n        alt,\n        "asset": asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      },\n      "location": city->{\n        _id,\n        name,\n        country\n      },\n      price\n    }': FEATURED_LISTINGS_QUERYResult;
    '\n  *[_type == "listing" && slug.current == $slug][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    name,\n    "slug": slug.current,\n    shortDescription,\n    longDescription,\n    category,\n    city->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    location { lat, lng },\n    primaryImage,\n    ecoTags,\n    digitalNomadFeatures,\n    lastVerifiedDate,\n    reviews[]->,\n    address,\n    website,\n    contactInfo,\n    openingHours,\n    shortDescription,\n    sourceUrls,\n        priceRange,\n    galleryImages[]{\n      ...,\n      asset->\n    }\n  }\n': LISTING_BY_SLUG_QUERYResult;
  }
}
