/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/api/amenities/route.ts
// Variable: query
// Query: *[_type == "amenity"]{ _id, name, description, badge{ asset->{ url } } }
export type QueryResult = Array<never>;

// Source: ./app/api/blog/[slug]/route.ts
// Variable: postQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    "primaryImage": primaryImage,    publishedAt,    excerpt,    body,    tags,    "authorName": author->name,    "authorImage": author->image,    "authorBio": author->bio,    "readingTime": round(length(pt::text(body)) / 200),    "relatedPosts": *[_type == "blogPost" && slug.current != $slug && count(tags[@ in ^.tags]) > 0] | order(publishedAt desc) [0...3] {      "slug": slug.current,      _id,      title,      "primaryImage": primaryImage,      publishedAt,      excerpt,      "authorName": author->name    },    _createdAt,    _updatedAt  }
export type PostQueryResult = null;

// Source: ./app/api/blog/route.ts
// Variable: postsQuery
// Query: *[_type == "blogPost" && defined(slug)] | order(publishedAt desc) [$start...$end] {    _id,    title,    slug,    "primaryImage": primaryImage,    publishedAt,    excerpt,    tags,    "authorName": author->name,    "authorImage": author->image,    "readingTime": round(length(pt::text(body)) / 200),    _updatedAt  }
export type PostsQueryResult = Array<never>;
// Variable: countQuery
// Query: count(*[_type == "blogPost" && defined(slug)])
export type CountQueryResult = number;

// Source: ./app/api/cities/route.ts
// Variable: CITIES_QUERY
// Query: *[_type == "city"] | order(_createdAt desc)[0...20] {      _id,      name,      "slug": slug.current,      country,      sustainabilityScore,      highlights,      "image": primaryImage { // TODO: rename field in schema to primaryImage later        alt,        _type,        "asset": asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      }    }
export type CITIES_QUERYResult = Array<never>;

// Source: ./app/api/featured-listings/route.ts
// Variable: FEATURED_LISTINGS_QUERY
// Query: *[_type == "listing" && moderation.featured == true && moderation.status == "published"] | order(_createdAt desc)[0...10] {      _id,      name,      "slug": slug.current,      "city": city->{ _id, name, "slug": slug.current, country },      "ecoFocusTags": ecoFocusTags[]->name,            "digitalNomadFeatures": digitalNomadFeatures[]->name,      "amenities": amenities[]-> {        _id,        name,        description,        badge{          asset->{            _id,            url,            metadata {              dimensions,              lqip            }          }        }      },      primaryImage,      galleryImages,      contactPhone,      contactEmail,      website,      priceRange,      type,      shortDescription,      address,      category,      location,      primaryImage{        alt,        asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      },      galleryImages[] {        alt,        asset->{          _id,          url,          metadata {            dimensions,            lqip          }        }      },      "imageUrl": primaryImage.asset->url,      coworkingDetails{        capacity,        pricingPlans[] { type, price, period },        openingHours[] { day, opens, closes }      },      accommodationDetails{        pricePerNightThb { min, max },        openingHours[] { day, opens, closes }      },      cafeDetails{        openingHours[] { day, opens, closes }      }    }
export type FEATURED_LISTINGS_QUERYResult = Array<never>;

// Source: ./src/lib/sanity/data.ts
// Variable: LISTING_BY_SLUG_QUERY
// Query: *[_type == "listing" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    city->{      _id,      name,      "slug": slug.current,      country    },    type,    category,    address,    location{lat, lng, alt},    primaryImage,    galleryImages,    ecoFocusTags[]->{      _id,      name    },    priceRange,    contactPhone,    contactEmail,    website,    shortDescription,    longDescription,    reviews[]->{      _id,      rating,      comment,      "userId": user._ref,      "user": user->{        name,        image      },      "createdAt": _createdAt    },    amenities[]->{      _id,      name,      description,      badge    },    coworkingDetails,    accommodationDetails,    cafeDetails,    restaurantDetails,    activitiesDetails,    digitalNomadFeatures[]->{      _id,      name,      slug,      description,      icon    },    moderation{status, featured, verificationStatus}  }
export type LISTING_BY_SLUG_QUERYResult = null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "amenity"]{ _id, name, description, badge{ asset->{ url } } }': QueryResult;
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    "primaryImage": primaryImage,\n    publishedAt,\n    excerpt,\n    body,\n    tags,\n    "authorName": author->name,\n    "authorImage": author->image,\n    "authorBio": author->bio,\n    "readingTime": round(length(pt::text(body)) / 200),\n    "relatedPosts": *[_type == "blogPost" && slug.current != $slug && count(tags[@ in ^.tags]) > 0] | order(publishedAt desc) [0...3] {\n      "slug": slug.current,\n      _id,\n      title,\n      "primaryImage": primaryImage,\n      publishedAt,\n      excerpt,\n      "authorName": author->name\n    },\n    _createdAt,\n    _updatedAt\n  }\n': PostQueryResult;
    '\n  *[_type == "blogPost" && defined(slug)] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    slug,\n    "primaryImage": primaryImage,\n    publishedAt,\n    excerpt,\n    tags,\n    "authorName": author->name,\n    "authorImage": author->image,\n    "readingTime": round(length(pt::text(body)) / 200),\n    _updatedAt\n  }\n': PostsQueryResult;
    'count(*[_type == "blogPost" && defined(slug)])': CountQueryResult;
    '*[_type == "city"] | order(_createdAt desc)[0...20] {\n      _id,\n      name,\n      "slug": slug.current,\n      country,\n      sustainabilityScore,\n      highlights,\n      "image": primaryImage { // TODO: rename field in schema to primaryImage later\n        alt,\n        _type,\n        "asset": asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      }\n    }': CITIES_QUERYResult;
    '*[_type == "listing" && moderation.featured == true && moderation.status == "published"] | order(_createdAt desc)[0...10] {\n      _id,\n      name,\n      "slug": slug.current,\n      "city": city->{ _id, name, "slug": slug.current, country },\n      "ecoFocusTags": ecoFocusTags[]->name,\n            "digitalNomadFeatures": digitalNomadFeatures[]->name,\n      "amenities": amenities[]-> {\n        _id,\n        name,\n        description,\n        badge{\n          asset->{\n            _id,\n            url,\n            metadata {\n              dimensions,\n              lqip\n            }\n          }\n        }\n      },\n      primaryImage,\n      galleryImages,\n      contactPhone,\n      contactEmail,\n      website,\n      priceRange,\n      type,\n      shortDescription,\n      address,\n      category,\n      location,\n      primaryImage{\n        alt,\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      },\n      galleryImages[] {\n        alt,\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions,\n            lqip\n          }\n        }\n      },\n      "imageUrl": primaryImage.asset->url,\n      coworkingDetails{\n        capacity,\n        pricingPlans[] { type, price, period },\n        openingHours[] { day, opens, closes }\n      },\n      accommodationDetails{\n        pricePerNightThb { min, max },\n        openingHours[] { day, opens, closes }\n      },\n      cafeDetails{\n        openingHours[] { day, opens, closes }\n      }\n    }': FEATURED_LISTINGS_QUERYResult;
    '\n  *[_type == "listing" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    city->{\n      _id,\n      name,\n      "slug": slug.current,\n      country\n    },\n    type,\n    category,\n    address,\n    location{lat, lng, alt},\n    primaryImage,\n    galleryImages,\n    ecoFocusTags[]->{\n      _id,\n      name\n    },\n    priceRange,\n    contactPhone,\n    contactEmail,\n    website,\n    shortDescription,\n    longDescription,\n    reviews[]->{\n      _id,\n      rating,\n      comment,\n      "userId": user._ref,\n      "user": user->{\n        name,\n        image\n      },\n      "createdAt": _createdAt\n    },\n    amenities[]->{\n      _id,\n      name,\n      description,\n      badge\n    },\n    coworkingDetails,\n    accommodationDetails,\n    cafeDetails,\n    restaurantDetails,\n    activitiesDetails,\n    digitalNomadFeatures[]->{\n      _id,\n      name,\n      slug,\n      description,\n      icon\n    },\n    moderation{status, featured, verificationStatus}\n  }\n': LISTING_BY_SLUG_QUERYResult;
  }
}
