#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
cd app-next-directory

echo "💅 Running Biome formatter..."
pnpm format

echo "🔍 Running type check..."
pnpm type-check

echo "🧹 Running Biome linter..."
pnpm lint:biome:fix

echo "✨ Pre-commit checks completed!"
