name: Security Audit

on:
  pull_request:
    paths:
      - 'sanity/**'
      - 'package.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - 'sanity/scripts/patch-prismjs.js'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd sanity
          npm ci
      - name: Run PrismJS Patch Script
        run: |
          cd sanity
          node scripts/patch-prismjs.js
      - name: Run Security Audit
        run: |
          cd sanity
          npm audit --audit-level=high
